<a href="https://colab.research.google.com/github/huramshina-l/learning.huramshina.2022/blob/main/numpy_solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# задание a

import numpy as np

In [ ]:
# задание b

b = np.zeros((2,5))

print(b)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# задание с


c = np.ones((5,2))

print(c)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# задание d

d = np.ones((10,1))*5

print(d)

[[5.]
 [5.]
 [5.]
 [5.]
 [5.]
 [5.]
 [5.]
 [5.]
 [5.]
 [5.]]


In [ ]:
# задание e

e = np.linspace(10,50,41)

print(e)


[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27.
 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45.
 46. 47. 48. 49. 50.]


In [ ]:
# задание f

f = np.arange(10,51,2)

print(f)


[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
# задание g

g = np.arange(0,9).reshape(3,3)

print(g)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# задание h
y = np.eye(3)

print(y)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# задание i

i = np.random.rand()

print(i)

0.33285679221102127


In [ ]:
# задание j

j = np.random.randn(5,5)

print(j)

[[ 0.05489165 -0.58444482 -0.04612669 -0.45366366  1.50974492]
 [-0.82827785  1.14870037 -0.07173403  2.0942605  -0.48571376]
 [-1.47486011  0.8880737   0.0935893  -1.05844092 -1.19943586]
 [-0.93323885 -0.01018325 -0.57491408  0.58619708  0.91047039]
 [ 1.00406317 -0.26896257  0.06550703  0.57375966  0.14405854]]


In [ ]:
# задание k


k = np.linspace(0.01, 1, 100).round(2).reshape(10,10)

print(k)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [ ]:
# задание l

mat = np.arange(1,26).reshape(5,5)

print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
print(mat[2:, 1:])

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [ ]:
# задание m

print(mat[3,4])

20


In [ ]:
# задание n

z = mat[0:3, 1].reshape(3,1)
print(z)

[[ 2]
 [ 7]
 [12]]


In [ ]:
# задание o
print(mat[4, :])

[21 22 23 24 25]


In [ ]:
# задание p

print(mat[3:5, :])

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
# задание q 

print(mat.sum())

325


In [ ]:
# задание r 

print(mat.std())

7.211102550927978


In [ ]:
# задание s.

print(mat.sum(axis=0))

[55 60 65 70 75]
